version: '3'
services:
 web:
    build: .
    image: appweb:1.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    container_name: app-flask-web
 db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    container_name: bd-mongo