apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-namespace
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80  # Puerto del servicio dentro del clúster de Kubernetes
      targetPort: 5000  # Puerto en el que la aplicación Flask está escuchando dentro del contenedor
  type: ClusterIP  # Tipo de servicio interno dentro del clúster de Kubernetes
